#version: "3.8"

services:
  qadb:
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    image: mysql:8
    container_name: mysql_container_db
    restart: always
    environment:
      MYSQL_DATABASE: my_qa_db # delete this will show error unknown database my_db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/backups   # shared backup folder


  fastapi_web:
    build: .
    depends_on:
      qadb:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backups:/backups   # same mount so both containers can see backups

    env_file:
      - .env

volumes:
  db_data: