"""update timing to before_meal in medicine table

Revision ID: 7934544b88d2
Revises: 
Create Date: 2026-03-09 12:58:06.455707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7934544b88d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('before_meal', sa.Boolean(), nullable=True))
    op.drop_column('medicines', 'timing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('timing', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('medicines', 'before_meal')
    # ### end Alembic commands ###
