"""Add new fields to User model

Revision ID: 045b8cfeaac7
Revises: dfcbae29ae02
Create Date: 2025-08-08 01:22:38.089400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '045b8cfeaac7'
down_revision: Union[str, Sequence[str], None] = 'dfcbae29ae02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=15), nullable=False))
    op.add_column('users', sa.Column('country', sa.String(length=255), nullable=False))
    op.alter_column('users', 'contact_number',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', mysql.TEXT(), nullable=True))
    op.alter_column('users', 'contact_number',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('users', 'country')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
